{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "agent-gateway" }}
  namespace: {{ .Values.namespace | default "agentgateway-system" }}
  labels:
    app: agent-gateway
    version: {{ .Chart.AppVersion | quote }}
{{- end }}
