# -*- coding: utf-8 -*-
"""MultiAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADV7MJb8g1lFy-DUCpufQe0a3LstuOM_
"""

pip install -r requirements.txt

import os
from typing import Annotated, List, TypedDict, Sequence, Literal
from weakref import finalize
from dotenv import load_dotenv
from langchain_community.vectorstores import FAISS
from langchain_community.document_loaders import TextLoader, WebBaseLoader
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langgraph.graph import StateGraph, START,END, add_messages
from langgraph.prebuilt import create_react_agent
from pydantic import BaseModel, Field
from langchain.chat_models import init_chat_model
from langchain_tavily import TavilySearch
from langchain_core.tools import Tool
from langchain_community.tools import WikipediaQueryRun
from langchain_community.utilities import WikipediaAPIWrapper
from langgraph.types import Command

from google.colab import userdata
os.environ["OPENAI_API_KEY"]=userdata.get('OPENAI_API_KEY')
os.environ["TAVILY_API_KEY"]=userdata.get('TAVILY_API_KEY')

# Initialize the LLM
llm = ChatOpenAI(model="gpt-4o")

tavily_tool = TavilySearch(max_results=5)

import langchain_core.tools

# Generic Function to create a retrieval tool
def make_retrieval_tool_from_text(file, name, desc):
    docs = TextLoader(file, encoding="utf-8").load()
    chunks = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50).split_documents(docs)
    vs = FAISS.from_documents(chunks, OpenAIEmbeddings())
    retriever = vs.as_retriever()

    def tool_func(query: str) -> str:
        print(f"Using Tool: {name}")
        results = retriever.invoke(query)
        return "\n\n".join(doc.page_content for doc in results)

    return langchain_core.tools.Tool(name=name, description=desc, func=tool_func)

internal_tool_1=make_retrieval_tool_from_text("/content/drive/MyDrive/Colab Notebooks/Krish_Nayak/sample_text.txt","InternalResearchNotes","Search internal research notes for experimental results")

#Get next node
def get_next_node(last_message: BaseMessage, goto:str):
  if "FINAL ANSWER" in last_message.content:
    #Any Agent decided the work is done
    return END
  else:
    return goto

def make_system_prompt(suffix:str) -> str:
  return (
      "You are a helpful AI assistant, collaborating with other assistants."
      " Use the provided tools to progress towards answering the question"
      " If you are unable to fully answer, that's OK, another assistant with different tools "
      " will help where you left off. Execute what you can to make progress. "
      " If you or any of the other assistants have the final answer or deliverable,"
      " prefix your responses with FINAL ANSWER so the team knows to stop. "
      f"\n{suffix}"
      )

#Research agent and node
research_agent = create_react_agent(llm,tools=[internal_tool_1,tavily_tool],
                                    prompt=make_system_prompt("You can only do research. Use the tool that you are binded with, you can use both of them" \
                                                              " You are working with a content writer colleague."))

research_agent

from langgraph.graph import MessagesState

#Research Node
def research_node(state: MessagesState) -> Command[Literal["blog_generator", END]]:
  result = research_agent.invoke(state)
  goto = get_next_node(result["messages"][-1], "blog_generator")

  #Wrap in a human message, as not all providers allow
  #AI Message at the last position of the input messages list
  result["messages"][-1] = HumanMessage(content=result["messages"][-1].content,name="researcher")
  return Command(update={"messages": result["messages"]}, goto=goto)

#Blog write agent
blog_agent=create_react_agent(llm,tools=[],prompt=make_system_prompt("You can only write a detailed blog. You are working with a researcher colleague."))

def blog_node(state:MessagesState)->Command[Literal["researcher",END]]:
  result=blog_agent.invoke(state)
  goto=get_next_node(result["messages"][-1],"researcher")
  #Wrap in a human message, as not all providers allow
  #AI message at the last position of the input messages list
  result["messages"][-1] = HumanMessage(content=result["messages"][-1].content,name="blog_generator")
  return Command(update={"messages":result["messages"]},goto=goto)

#Build LangGraph DAG
workflow = StateGraph(MessagesState)
workflow.add_node("researcher",research_node)
workflow.add_node("blog_generator",blog_node)
workflow.add_edge(START,"researcher")
graph=workflow.compile()

graph

results = graph.invoke({"messages":"Write a detailed blog on transformer variants in production deployments."})

print(f"Results: {results['messages'][-1]}")