# -*- coding: utf-8 -*-
"""2-supervisor_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cdx9Q3QmJTDKfiauM8DhtEObe3y4BdH-
"""

import os
from typing import Annotated, List, TypedDict, Sequence, Literal
from weakref import finalize
from dotenv import load_dotenv
from langchain_community.vectorstores import FAISS
from langchain_community.document_loaders import TextLoader, WebBaseLoader
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langgraph.graph import StateGraph, START,END, add_messages
from langgraph.prebuilt import create_react_agent
from pydantic import BaseModel, Field
from langchain.chat_models import init_chat_model
from langchain_tavily import TavilySearch
from langchain_core.tools import Tool
from langchain_community.tools import WikipediaQueryRun
from langchain_community.utilities import WikipediaAPIWrapper
from langgraph.types import Command
import langchain_core.tools
from langgraph_supervisor import create_supervisor

from google.colab import userdata
os.environ["OPENAI_API_KEY"]=userdata.get('OPENAI_API_KEY')
os.environ["TAVILY_API_KEY"]=userdata.get('TAVILY_API_KEY')

llm = ChatOpenAI(model="gpt-4o")
web_search = TavilySearch(max_results=5)

def make_retrieval_tool_from_text(file, name, desc):
    docs = TextLoader(file, encoding="utf-8").load()
    chunks = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50).split_documents(docs)
    vs = FAISS.from_documents(chunks, OpenAIEmbeddings())
    retriever = vs.as_retriever()

    def tool_func(query: str) -> str:
        print(f"Using Tool: {name}")
        results = retriever.invoke(query)
        return "\n\n".join(doc.page_content for doc in results)

    return langchain_core.tools.Tool(name=name, description=desc, func=tool_func)

internal_tool_1=make_retrieval_tool_from_text("/content/drive/MyDrive/Colab Notebooks/Krish_Nayak/sample_text.txt","InternalResearchNotes","Search internal research notes for experimental results")

research_agent=create_react_agent(model=llm,tools=[web_search,internal_tool_1],prompt=("You are a research agent.\n\n"
"INSTRUCTIONS: \n"
"- Assist ONLY with research-related tasks, DO NOT do any math \n"
"- After you're done with your tasks, respond to the supervisor directly"
"- Respond ONLY with the results of your work, do NOT include ANY other text"),
name="research_agent")
research_agent

def add(a:float,b:float):
  """Add two numbers"""
  print("Using ADD")
  return a+b

def subtracr(a:float,b:float):
  """Add two numbers"""
  print("Using Subtract")
  return a-b

def multiply(a:float,b:float):
  """Multiply two numbers"""
  print("Using Multiply")
  return a*b

def divide(a:float,b:float):
  """Divide two numbers"""
  print("Using Divide")
  return a/b

math_agent=create_react_agent(model=llm,tools=[add,multiply,divide],prompt=("You are a math agent.\n\n"
  "INSTRUCTIONS:\n"
  "- Assist ONLY with math-related tasks\n"
  "- After you're done with your tasks, respond to the supervisor directly\n"
  "- Respond ONLY with the results of your work, do NOT include ANY other text."),
  name="math_agent")

#Create Supervisor Agent
supervisor=create_supervisor(model=llm,
                             agents=[research_agent,math_agent],
                             prompt=("You are a supervisor managing two agents"
"- A research agent. Assign research-related tasks to this agent\n"
"- A math agent. Assign math-related tasks to this agent\n"
"Assign work to one agent at a time, do not call agents in parallel.\n"
"Do not do any work yourself."),
add_handoff_back_messages=True,
output_mode="full_history"
).compile()

supervisor

response=supervisor.invoke({"messages":"List all the transformer variants in production deployments from the retriever and then tell what is 5 plus 10"})

response["messages"][-1].content