# -*- coding: utf-8 -*-
"""Iterative_Retrieval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UyxEPBbim8KwAnmEcDo6rlPp_0U0qkhh
"""

pip install -r requirements.txt

import os
from typing import Annotated, List, TypedDict, Sequence
from weakref import finalize
from dotenv import load_dotenv
from langchain_community.vectorstores import FAISS
from langchain_community.document_loaders import TextLoader, WebBaseLoader
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langgraph.graph import StateGraph, END, add_messages
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain.chat_models import init_chat_model

from google.colab import userdata
os.environ["OPENAI_API_KEY"]=userdata.get('OPENAI_API_KEY')

llm = init_chat_model("openai:gpt-4o")

import os
#Load and Embed Documents
# Ensure 'internal_docs.txt' exists in the current directory, or provide the full path to it.
# For demonstration, I'm using a sample file available in Colab.
docs = TextLoader("/content/drive/MyDrive/Colab Notebooks/Krish_Nayak/sample_text.txt",encoding="utf-8").load()
chunks = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50).split_documents(docs)
vectorstore=FAISS.from_documents(chunks,OpenAIEmbeddings())
retriever = vectorstore.as_retriever()

class IterativeRAGState(BaseModel):
  question: str
  refined_question: str = ""
  retrieved_docs: List[Document] = []
  answer: str = ""
  verified: bool = False
  attempts: int = 0

##Reflect and Verify
def generate_answer(state: IterativeRAGState):
  context = "\n\n".join(doc.page_content for doc in state.retrieved_docs)
  prompt = f"""Use the following context to answer the question

    Context:
    {context}

    Question:
    {state.question}

    """
  response = llm.invoke(prompt.strip()).content.strip()
  return state.model_copy(update={"answer":response, "attempts": state.attempts+1})

##Retrieve
def retrieve_docs(state: IterativeRAGState):
  query = state.refined_question or state.question
  docs = retriever.invoke(query)
  return state.model_copy(update={"retrieved_docs":docs})

#Reflect on answer
def reflect_on_answer(state: IterativeRAGState)-> IterativeRAGState:
  prompt = f"""
    Evaluate whether the answer below is factually sufficient and complete

    Question: {state.question}
    Answer: {state.answer}

    Respond 'YES'if it's complete, otherwise 'NO' with feedback
    """
  feedback=llm.invoke(prompt).content.lower()
  verified = "yes" in feedback
  return state.model_copy(update={"verified":verified})

#Refine Query
def refine_query(state:IterativeRAGState) -> IterativeRAGState:
  prompt=f"""
  The answer appears incomplete. Suggest a better version of the query that would help reviews more relevant context.
  Original Question: {state.question}
  Current Answer: {state.answer}
  """
  new_query = llm.invoke(prompt).content.strip()
  return state.model_copy(update={"refined_question":new_query})

#Create LangGraph DAG
builder = StateGraph(IterativeRAGState)
builder.add_node("retrieve",retrieve_docs)
builder.add_node("answer",generate_answer)
builder.add_node("reflect",reflect_on_answer)
builder.add_node("refine",refine_query)

builder.set_entry_point("retrieve")
builder.add_edge("retrieve","answer")
builder.add_edge("answer","reflect")
builder.add_conditional_edges("reflect",lambda s: END if s.verified or s.attempts >=2 else "refine")

builder.add_edge("refine","retrieve")
builder.add_edge("answer",END)
graph = builder.compile()

query = "What is Python and explain it's significance ?"
initial_state = IterativeRAGState(question=query)
final = graph.invoke(initial_state)

print("Final Answer:\n", final["answer"])
print("\n Verified: ",final["verified"])
print("Attempts: ", final["attempts"])