{{- range .Values.agents }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}-sa
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: financial-services
    agent: {{ .name }}
{{- end }}
