{{- if .Values.litellm.createApiKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.litellm.apiKeySecret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  {{ .Values.litellm.apiKeySecret.key }}: {{ .Values.litellm.apiKeyValue | quote }}
{{- end }}
