apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: cr.agentgateway.dev/charts
    chart: agentgateway
    targetRevision: v1.6.0
    helm:
      releaseName: agent-gateway
      skipCrds: false
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.agentGateway | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true